- name: installo i pacchetti base
  apt:
    name:
      - vim
      - rsync
      - htop
      - sysstat
    state: present
    update_cache: yes
  become: true

- name: rimuovo il pacchetto nano
  apt:
    name:
      - nano
    state: absent
    update_cache: yes
  become: true